# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2022-03-20 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20220320_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='req',
            new_name='request',
        ),
    ]
