# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2022-03-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_history_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
